class CreateFormularios < ActiveRecord::Migration[5.1]
  def change
    create_table :formularios do |t|
      t.string :nombre_encargado
      t.string :telefono
      t.date :fecha
      t.decimal :DI12
      t.decimal :DI13
      t.decimal :DI14
      t.decimal :DI15
      t.decimal :DI16
      t.decimal :DI17
      t.decimal :DI18
      t.decimal :DI19
      t.decimal :DI20
      t.decimal :DI21
      t.decimal :DI22
      t.decimal :DI23
      t.decimal :DI24
      t.decimal :DI25
      t.decimal :DI26
      t.decimal :DI27
      t.decimal :DI28
      t.decimal :DI29
      t.string :DI30
      t.decimal :DI31
      t.string :DI32
      t.decimal :DI33
      t.string :DI34
      t.decimal :DI35
      t.string :GOB1_1
      t.string :GOB1_2
      t.string :GOB1_3
      t.string :GOB1_4
      t.string :GOB1_5
      t.string :GOB1_6
      t.string :GOB1_7
      t.string :GOB1_8
      t.string :GOB2_1
      t.string :GOB2_2
      t.string :GOB2_3
      t.string :GOB2_4
      t.string :GOB2_5
      t.string :GOB2_6
      t.string :GOB2_7
      t.string :GOB2_8
      t.string :GOB2_9
      t.string :GOB3_1
      t.string :GOB3_2
      t.string :GOB3_3
      t.string :GOB3_4
      t.string :GOB3_5
      t.string :GOB3_6
      t.string :GOB3_7
      t.string :GOB3_8
      t.string :GOB3_9
      t.string :GOB3_10
      t.string :GOB3_11
      t.string :GOB3_12
      t.string :GOB3_13
      t.string :GOB3_14
      t.string :GOB3_15
      t.string :GOB4_1
      t.string :GOB4_2
      t.string :GOB4_3
      t.string :GOB4_4
      t.string :GOB4_5
      t.string :GOB5_1
      t.string :GOB5_2
      t.string :GOB5_3
      t.string :GOB5_4
      t.string :GOB5_5
      t.string :GOB5_6
      t.string :GOB5_7
      t.string :GOB5_8
      t.string :GOB5_9
      t.string :GOB6_1
      t.string :GOB6_2
      t.string :DGOB1_1
      t.string :DGOB1_2
      t.string :DGOB1_3
      t.string :DGOB1_4
      t.string :DGOB1_5
      t.string :DGOB1_6
      t.string :DGOB1_7
      t.string :DGOB1_8
      t.string :DGOB2_1
      t.string :DGOB2_2
      t.string :DGOB2_3
      t.string :DGOB2_4
      t.string :DGOB2_5
      t.string :DGOB2_6
      t.string :DGOB2_7
      t.string :DGOB2_8
      t.string :DGOB2_9
      t.string :DGOB3_1
      t.string :DGOB3_2
      t.string :DGOB3_3
      t.string :DGOB3_4
      t.string :DGOB3_5
      t.string :DGOB3_6
      t.string :DGOB3_7
      t.string :DGOB3_8
      t.string :DGOB3_9
      t.string :DGOB3_10
      t.string :DGOB3_11
      t.string :DGOB3_12
      t.string :DGOB3_13
      t.string :DGOB3_14
      t.string :DGOB3_15
      t.string :DGOB4_1
      t.string :DGOB4_2
      t.string :DGOB4_3
      t.string :DGOB4_4
      t.string :DGOB4_5
      t.string :DGOB5_1
      t.string :DGOB5_2
      t.string :DGOB5_3
      t.string :DGOB5_4
      t.string :DGOB5_5
      t.string :DGOB5_6
      t.string :DGOB5_7
      t.string :DGOB5_8
      t.string :DGOB5_9
      t.string :DGOB6_1
      t.string :DGOB6_2
      t.string :VGOB1_1
      t.string :VGOB1_2
      t.string :VGOB1_3
      t.string :VGOB1_4
      t.string :VGOB1_5
      t.string :VGOB1_6
      t.string :VGOB1_7
      t.string :VGOB1_8
      t.string :VGOB2_1
      t.string :VGOB2_2
      t.string :VGOB2_3
      t.string :VGOB2_4
      t.string :VGOB2_5
      t.string :VGOB2_6
      t.string :VGOB2_7
      t.string :VGOB2_8
      t.string :VGOB2_9
      t.string :VGOB3_1
      t.string :VGOB3_2
      t.string :VGOB3_3
      t.string :VGOB3_4
      t.string :VGOB3_5
      t.string :VGOB3_6
      t.string :VGOB3_7
      t.string :VGOB3_8
      t.string :VGOB3_9
      t.string :VGOB3_10
      t.string :VGOB3_11
      t.string :VGOB3_12
      t.string :VGOB3_13
      t.string :VGOB3_14
      t.string :VGOB3_15
      t.string :VGOB4_1
      t.string :VGOB4_2
      t.string :VGOB4_3
      t.string :VGOB4_4
      t.string :VGOB4_5
      t.string :VGOB5_1
      t.string :VGOB5_2
      t.string :VGOB5_3
      t.string :VGOB5_4
      t.string :VGOB5_5
      t.string :VGOB5_6
      t.string :VGOB5_7
      t.string :VGOB5_8
      t.string :VGOB5_9
      t.string :VGOB6_1
      t.string :VGOB6_2
      t.string :CGOB1_1
      t.string :CGOB1_2
      t.string :CGOB1_3
      t.string :CGOB1_4
      t.string :CGOB1_5
      t.string :CGOB1_6
      t.string :CGOB1_7
      t.string :CGOB1_8
      t.string :CGOB2_1
      t.string :CGOB2_2
      t.string :CGOB2_3
      t.string :CGOB2_4
      t.string :CGOB2_5
      t.string :CGOB2_6
      t.string :CGOB2_7
      t.string :CGOB2_8
      t.string :CGOB2_9
      t.string :CGOB3_1
      t.string :CGOB3_2
      t.string :CGOB3_3
      t.string :CGOB3_4
      t.string :CGOB3_5
      t.string :CGOB3_6
      t.string :CGOB3_7
      t.string :CGOB3_8
      t.string :CGOB3_9
      t.string :CGOB3_10
      t.string :CGOB3_11
      t.string :CGOB3_12
      t.string :CGOB3_13
      t.string :CGOB3_14
      t.string :CGOB3_15
      t.string :CGOB4_1
      t.string :CGOB4_2
      t.string :CGOB4_3
      t.string :CGOB4_4
      t.string :CGOB4_5
      t.string :CGOB5_1
      t.string :CGOB5_2
      t.string :CGOB5_3
      t.string :CGOB5_4
      t.string :CGOB5_5
      t.string :CGOB5_6
      t.string :CGOB5_7
      t.string :CGOB5_8
      t.string :CGOB5_9
      t.string :CGOB6_1
      t.string :CGOB6_2
      t.string :CU1_1
      t.string :CU1_2
      t.string :CU1_3
      t.string :CU1_4
      t.string :CU1_5
      t.string :CU2_1
      t.string :CU2_2
      t.string :CU3_1
      t.string :CU3_2
      t.string :CU3_3
      t.string :CU3_4
      t.string :CU3_5
      t.string :CU4_1
      t.string :CU4_2
      t.string :CU5_1
      t.string :CU5_2
      t.string :CU5_3
      t.string :CU6_1
      t.string :CU6_2
      t.string :CU7_1
      t.string :CU7_2
      t.string :CU7_3
      t.string :CU7_4
      t.string :CU7_5
      t.string :CU7_6
      t.string :CU7_7
      t.string :CU7_8
      t.string :DCU1_1
      t.string :DCU1_2
      t.string :DCU1_3
      t.string :DCU1_4
      t.string :DCU1_5
      t.string :DCU2_1
      t.string :DCU2_2
      t.string :DCU3_1
      t.string :DCU3_2
      t.string :DCU3_3
      t.string :DCU3_4
      t.string :DCU3_5
      t.string :DCU4_1
      t.string :DCU4_2
      t.string :DCU5_1
      t.string :DCU5_2
      t.string :DCU5_3
      t.string :DCU6_1
      t.string :DCU6_2
      t.string :DCU7_1
      t.string :DCU7_2
      t.string :DCU7_3
      t.string :DCU7_4
      t.string :DCU7_5
      t.string :DCU7_6
      t.string :DCU7_7
      t.string :DCU7_8
      t.string :VCU1_1
      t.string :VCU1_2
      t.string :VCU1_3
      t.string :VCU1_4
      t.string :VCU1_5
      t.string :VCU2_1
      t.string :VCU2_2
      t.string :VCU3_1
      t.string :VCU3_2
      t.string :VCU3_3
      t.string :VCU3_4
      t.string :VCU3_5
      t.string :VCU4_1
      t.string :VCU4_2
      t.string :VCU5_1
      t.string :VCU5_2
      t.string :VCU5_3
      t.string :VCU6_1
      t.string :VCU6_2
      t.string :VCU7_1
      t.string :VCU7_2
      t.string :VCU7_3
      t.string :VCU7_4
      t.string :VCU7_5
      t.string :VCU7_6
      t.string :VCU7_7
      t.string :VCU7_8
      t.string :CCU1_1
      t.string :CCU1_2
      t.string :CCU1_3
      t.string :CCU1_4
      t.string :CCU1_5
      t.string :CCU2_1
      t.string :CCU2_2
      t.string :CCU3_1
      t.string :CCU3_2
      t.string :CCU3_3
      t.string :CCU3_4
      t.string :CCU3_5
      t.string :CCU4_1
      t.string :CCU4_2
      t.string :CCU5_1
      t.string :CCU5_2
      t.string :CCU5_3
      t.string :CCU6_1
      t.string :CCU6_2
      t.string :CCU7_1
      t.string :CCU7_2
      t.string :CCU7_3
      t.string :CCU7_4
      t.string :CCU7_5
      t.string :CCU7_6
      t.string :CCU7_7
      t.string :CCU7_8
      t.string :AC1_1
      t.string :AC1_2
      t.string :AC1_3
      t.string :AC2_1
      t.string :AC2_2
      t.string :AC2_3
      t.string :AC2_4
      t.string :AC2_5
      t.string :AC2_6
      t.string :AC2_7
      t.string :AC2_8
      t.string :AC3_1
      t.string :AC3_2
      t.string :AC4_1
      t.string :AC5_1
      t.string :AC6_1
      t.string :AC6_2
      t.string :AC7_1
      t.string :AC7_2
      t.string :AC7_3
      t.string :AC8_1
      t.string :AC8_2
      t.string :AC8_3
      t.string :AC8_4
      t.string :AC8_5
      t.string :DAC1_1
      t.string :DAC1_2
      t.string :DAC1_3
      t.string :DAC2_1
      t.string :DAC2_2
      t.string :DAC2_3
      t.string :DAC2_4
      t.string :DAC2_5
      t.string :DAC2_6
      t.string :DAC2_7
      t.string :DAC2_8
      t.string :DAC3_1
      t.string :DAC3_2
      t.string :DAC4_1
      t.string :DAC5_1
      t.string :DAC6_1
      t.string :DAC6_2
      t.string :DAC7_1
      t.string :DAC7_2
      t.string :DAC7_3
      t.string :DAC8_1
      t.string :DAC8_2
      t.string :DAC8_3
      t.string :DAC8_4
      t.string :DAC8_5
      t.string :VAC1_1
      t.string :VAC1_2
      t.string :VAC1_3
      t.string :VAC2_1
      t.string :VAC2_2
      t.string :VAC2_3
      t.string :VAC2_4
      t.string :VAC2_5
      t.string :VAC2_6
      t.string :VAC2_7
      t.string :VAC2_8
      t.string :VAC3_1
      t.string :VAC3_2
      t.string :VAC4_1
      t.string :VAC5_1
      t.string :VAC6_1
      t.string :VAC6_2
      t.string :VAC7_1
      t.string :VAC7_2
      t.string :VAC7_3
      t.string :VAC8_1
      t.string :VAC8_2
      t.string :VAC8_3
      t.string :VAC8_4
      t.string :VAC8_5
      t.string :CAC1_1
      t.string :CAC1_2
      t.string :CAC1_3
      t.string :CAC2_1
      t.string :CAC2_2
      t.string :CAC2_3
      t.string :CAC2_4
      t.string :CAC2_5
      t.string :CAC2_6
      t.string :CAC2_7
      t.string :CAC2_8
      t.string :CAC3_1
      t.string :CAC3_2
      t.string :CAC4_1
      t.string :CAC5_1
      t.string :CAC6_1
      t.string :CAC6_2
      t.string :CAC7_1
      t.string :CAC7_2
      t.string :CAC7_3
      t.string :CAC8_1
      t.string :CAC8_2
      t.string :CAC8_3
      t.string :CAC8_4
      t.string :CAC8_5
      t.string :GC1_1
      t.string :GC1_2
      t.string :GC2_1
      t.string :GC2_2
      t.string :GC2_3
      t.string :GC2_4
      t.string :GC2_5
      t.string :GC2_6
      t.string :GC2_7
      t.string :GC2_8
      t.string :GC2_9
      t.string :GC2_10
      t.string :GC3_1
      t.string :GC3_2
      t.string :GC3_3
      t.string :GC3_4
      t.string :GC3_5
      t.string :GC3_6
      t.string :GC3_7
      t.string :GC3_8
      t.string :GC4_1
      t.string :GC4_2
      t.string :GC4_3
      t.string :GC4_4
      t.string :GC4_5
      t.string :GC4_6
      t.string :GC4_7
      t.string :GC4_8
      t.string :GC5_1
      t.string :GC5_2
      t.string :GC5_3
      t.string :GC5_4
      t.string :GC5_5
      t.string :GC5_6
      t.string :GC5_7
      t.string :GC5_8
      t.string :GC5_9
      t.string :GC5_10
      t.string :GC6_1
      t.string :GC6_2
      t.string :GC6_3
      t.string :GC6_4
      t.string :GC6_5
      t.string :GC6_6
      t.string :GC7_1
      t.string :GC7_2
      t.string :GC7_3
      t.string :GC8_1
      t.string :GC8_2
      t.string :GC8_3
      t.string :GC8_4
      t.string :GC8_5
      t.string :GC8_6
      t.string :GC8_7
      t.string :GC9_1
      t.string :GC9_2
      t.string :GC9_3
      t.string :GC9_4
      t.string :GC9_5
      t.string :GC9_6
      t.string :GC9_7
      t.string :GC9_8
      t.string :GC9_9
      t.string :GC9_10
      t.string :GC10_1
      t.string :GC10_2
      t.string :GC11_1
      t.string :GC11_2
      t.string :GC12_1
      t.string :GC12_2
      t.string :GC12_3
      t.string :GC13_1
      t.string :GC13_2
      t.string :GC14_1
      t.string :GC14_2
      t.string :GC14_3
      t.string :GC14_4
      t.string :GC15_1
      t.string :GC15_2
      t.string :GC15_3
      t.string :GC15_4
      t.string :GC15_5
      t.string :GC15_6
      t.string :GC15_7
      t.string :DGC1_1
      t.string :DGC1_2
      t.string :DGC2_1
      t.string :DGC2_2
      t.string :DGC2_3
      t.string :DGC2_4
      t.string :DGC2_5
      t.string :DGC2_6
      t.string :DGC2_7
      t.string :DGC2_8
      t.string :DGC2_9
      t.string :DGC2_10
      t.string :DGC3_1
      t.string :DGC3_2
      t.string :DGC3_3
      t.string :DGC3_4
      t.string :DGC3_5
      t.string :DGC3_6
      t.string :DGC3_7
      t.string :DGC3_8
      t.string :DGC4_1
      t.string :DGC4_2
      t.string :DGC4_3
      t.string :DGC4_4
      t.string :DGC4_5
      t.string :DGC4_6
      t.string :DGC4_7
      t.string :DGC4_8
      t.string :DGC5_1
      t.string :DGC5_2
      t.string :DGC5_3
      t.string :DGC5_4
      t.string :DGC5_5
      t.string :DGC5_6
      t.string :DGC5_7
      t.string :DGC5_8
      t.string :DGC5_9
      t.string :DGC5_10
      t.string :DGC6_1
      t.string :DGC6_2
      t.string :DGC6_3
      t.string :DGC6_4
      t.string :DGC6_5
      t.string :DGC6_6
      t.string :DGC7_1
      t.string :DGC7_2
      t.string :DGC7_3
      t.string :DGC8_1
      t.string :DGC8_2
      t.string :DGC8_3
      t.string :DGC8_4
      t.string :DGC8_5
      t.string :DGC8_6
      t.string :DGC8_7
      t.string :DGC9_1
      t.string :DGC9_2
      t.string :DGC9_3
      t.string :DGC9_4
      t.string :DGC9_5
      t.string :DGC9_6
      t.string :DGC9_7
      t.string :DGC9_8
      t.string :DGC9_9
      t.string :DGC9_10
      t.string :DGC10_1
      t.string :DGC10_2
      t.string :DGC11_1
      t.string :DGC11_2
      t.string :DGC12_1
      t.string :DGC12_2
      t.string :DGC12_3
      t.string :DGC13_1
      t.string :DGC13_2
      t.string :DGC14_1
      t.string :DGC14_2
      t.string :DGC14_3
      t.string :DGC14_4
      t.string :DGC15_1
      t.string :DGC15_2
      t.string :DGC15_3
      t.string :DGC15_4
      t.string :DGC15_5
      t.string :DGC15_6
      t.string :DGC15_7
      t.string :VGC1_1
      t.string :VGC1_2
      t.string :VGC2_1
      t.string :VGC2_2
      t.string :VGC2_3
      t.string :VGC2_4
      t.string :VGC2_5
      t.string :VGC2_6
      t.string :VGC2_7
      t.string :VGC2_8
      t.string :VGC2_9
      t.string :VGC2_10
      t.string :VGC3_1
      t.string :VGC3_2
      t.string :VGC3_3
      t.string :VGC3_4
      t.string :VGC3_5
      t.string :VGC3_6
      t.string :VGC3_7
      t.string :VGC3_8
      t.string :VGC4_1
      t.string :VGC4_2
      t.string :VGC4_3
      t.string :VGC4_4
      t.string :VGC4_5
      t.string :VGC4_6
      t.string :VGC4_7
      t.string :VGC4_8
      t.string :VGC5_1
      t.string :VGC5_2
      t.string :VGC5_3
      t.string :VGC5_4
      t.string :VGC5_5
      t.string :VGC5_6
      t.string :VGC5_7
      t.string :VGC5_8
      t.string :VGC5_9
      t.string :VGC5_10
      t.string :VGC6_1
      t.string :VGC6_2
      t.string :VGC6_3
      t.string :VGC6_4
      t.string :VGC6_5
      t.string :VGC6_6
      t.string :VGC7_1
      t.string :VGC7_2
      t.string :VGC7_3
      t.string :VGC8_1
      t.string :VGC8_2
      t.string :VGC8_3
      t.string :VGC8_4
      t.string :VGC8_5
      t.string :VGC8_6
      t.string :VGC8_7
      t.string :VGC9_1
      t.string :VGC9_2
      t.string :VGC9_3
      t.string :VGC9_4
      t.string :VGC9_5
      t.string :VGC9_6
      t.string :VGC9_7
      t.string :VGC9_8
      t.string :VGC9_9
      t.string :VGC9_10
      t.string :VGC10_1
      t.string :VGC10_2
      t.string :VGC11_1
      t.string :VGC11_2
      t.string :VGC12_1
      t.string :VGC12_2
      t.string :VGC12_3
      t.string :VGC13_1
      t.string :VGC13_2
      t.string :VGC14_1
      t.string :VGC14_2
      t.string :VGC14_3
      t.string :VGC14_4
      t.string :VGC15_1
      t.string :VGC15_2
      t.string :VGC15_3
      t.string :VGC15_4
      t.string :VGC15_5
      t.string :VGC15_6
      t.string :VGC15_7
      t.string :CGC1_1
      t.string :CGC1_2
      t.string :CGC2_1
      t.string :CGC2_2
      t.string :CGC2_3
      t.string :CGC2_4
      t.string :CGC2_5
      t.string :CGC2_6
      t.string :CGC2_7
      t.string :CGC2_8
      t.string :CGC2_9
      t.string :CGC2_10
      t.string :CGC3_1
      t.string :CGC3_2
      t.string :CGC3_3
      t.string :CGC3_4
      t.string :CGC3_5
      t.string :CGC3_6
      t.string :CGC3_7
      t.string :CGC3_8
      t.string :CGC4_1
      t.string :CGC4_2
      t.string :CGC4_3
      t.string :CGC4_4
      t.string :CGC4_5
      t.string :CGC4_6
      t.string :CGC4_7
      t.string :CGC4_8
      t.string :CGC5_1
      t.string :CGC5_2
      t.string :CGC5_3
      t.string :CGC5_4
      t.string :CGC5_5
      t.string :CGC5_6
      t.string :CGC5_7
      t.string :CGC5_8
      t.string :CGC5_9
      t.string :CGC5_10
      t.string :CGC6_1
      t.string :CGC6_2
      t.string :CGC6_3
      t.string :CGC6_4
      t.string :CGC6_5
      t.string :CGC6_6
      t.string :CGC7_1
      t.string :CGC7_2
      t.string :CGC7_3
      t.string :CGC8_1
      t.string :CGC8_2
      t.string :CGC8_3
      t.string :CGC8_4
      t.string :CGC8_5
      t.string :CGC8_6
      t.string :CGC8_7
      t.string :CGC9_1
      t.string :CGC9_2
      t.string :CGC9_3
      t.string :CGC9_4
      t.string :CGC9_5
      t.string :CGC9_6
      t.string :CGC9_7
      t.string :CGC9_8
      t.string :CGC9_9
      t.string :CGC9_10
      t.string :CGC10_1
      t.string :CGC10_2
      t.string :CGC11_1
      t.string :CGC11_2
      t.string :CGC12_1
      t.string :CGC12_2
      t.string :CGC12_3
      t.string :CGC13_1
      t.string :CGC13_2
      t.string :CGC14_1
      t.string :CGC14_2
      t.string :CGC14_3
      t.string :CGC14_4
      t.string :CGC15_1
      t.string :CGC15_2
      t.string :CGC15_3
      t.string :CGC15_4
      t.string :CGC15_5
      t.string :CGC15_6
      t.string :CGC15_7
      t.string :RS1_1
      t.string :RS1_2
      t.string :RS2_1
      t.string :RS2_2
      t.string :RS2_3
      t.string :RS2_4
      t.string :RS3_1
      t.string :RS3_2
      t.string :RS4_1
      t.string :RS4_2
      t.string :RS4_3
      t.string :RS4_4
      t.string :RS4_5
      t.string :RS5_1
      t.string :RS5_2
      t.string :RS5_3
      t.string :RS6_1
      t.string :RS6_2
      t.string :RS6_3
      t.string :RS7_1
      t.string :RS7_2
      t.string :RS7_3
      t.string :RS8_1
      t.string :RS8_2
      t.string :RS8_3
      t.string :RS9_1
      t.string :DRS1_1
      t.string :DRS1_2
      t.string :DRS2_1
      t.string :DRS2_2
      t.string :DRS2_3
      t.string :DRS2_4
      t.string :DRS3_1
      t.string :DRS3_2
      t.string :DRS4_1
      t.string :DRS4_2
      t.string :DRS4_3
      t.string :DRS4_4
      t.string :DRS4_5
      t.string :DRS5_1
      t.string :DRS5_2
      t.string :DRS5_3
      t.string :DRS6_1
      t.string :DRS6_2
      t.string :DRS6_3
      t.string :DRS7_1
      t.string :DRS7_2
      t.string :DRS7_3
      t.string :DRS8_1
      t.string :DRS8_2
      t.string :DRS8_3
      t.string :DRS9_1
      t.string :VRS1_1
      t.string :VRS1_2
      t.string :VRS2_1
      t.string :VRS2_2
      t.string :VRS2_3
      t.string :VRS2_4
      t.string :VRS3_1
      t.string :VRS3_2
      t.string :VRS4_1
      t.string :VRS4_2
      t.string :VRS4_3
      t.string :VRS4_4
      t.string :VRS4_5
      t.string :VRS5_1
      t.string :VRS5_2
      t.string :VRS5_3
      t.string :VRS6_1
      t.string :VRS6_2
      t.string :VRS6_3
      t.string :VRS7_1
      t.string :VRS7_2
      t.string :VRS7_3
      t.string :VRS8_1
      t.string :VRS8_2
      t.string :VRS8_3
      t.string :VRS9_1
      t.string :CRS1_1
      t.string :CRS1_2
      t.string :CRS2_1
      t.string :CRS2_2
      t.string :CRS2_3
      t.string :CRS2_4
      t.string :CRS3_1
      t.string :CRS3_2
      t.string :CRS4_1
      t.string :CRS4_2
      t.string :CRS4_3
      t.string :CRS4_4
      t.string :CRS4_5
      t.string :CRS5_1
      t.string :CRS5_2
      t.string :CRS5_3
      t.string :CRS6_1
      t.string :CRS6_2
      t.string :CRS6_3
      t.string :CRS7_1
      t.string :CRS7_2
      t.string :CRS7_3
      t.string :CRS8_1
      t.string :CRS8_2
      t.string :CRS8_3
      t.string :CRS9_1
      t.integer :ct_total

      t.timestamps
    end
  end
end
